name: IaC

on:
  workflow_call:
    inputs:
      artifactNameAPI:
        required: true
        type: string
      artifactNameSqlMigration:
        required: true
        type: string
      artifactNameSqlAzureAdPermissions:
        required: true
        type: string
      artifactNameTerraform:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_SQL_INSTANCE_NAME:
        required: true
      AZURE_SQL_DATABASE_PRODUCTCATALOGUE_CONNECTION_STRING:
        required: true
      AZURE_SQL_SERVER_AD_ADMIN_OBJECT_ID:
        required: true
      AZURE_SQL_SERVER_AD_ADMIN_USERNAME:
        required: true
    outputs:
      static_website_url:
        value: ${{ jobs.infrastructure_create.outputs.static_website_url }}
      static_webapp_api_key: 
        value: ${{ jobs.infrastructure_create.outputs.static_webapp_api_key }}
      api_app_name: 
        value: ${{ jobs.infrastructure_create.outputs.api_app_name }}
      resource_group_name: 
        value: ${{ jobs.infrastructure_create.outputs.resource_group_name }}

jobs:
  infrastructure_create:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      static_website_url: ${{ steps.apply.outputs.static_website_url }}
      static_webapp_api_key: ${{ steps.get_config_key.outputs.api_key }}
      api_app_name: ${{ steps.apply.outputs.api_app_name }}
      resource_group_name: ${{ steps.apply.outputs.resource_group_name }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_wrapper: false

      - name: Terraform Init Main
        id: init
        working-directory: "./artifacts/${{inputs.artifactNameTerraform}}"
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Plan Main
        id: plan
        working-directory: "./artifacts/${{ inputs.artifactNameTerraform }}"
        run: > 
          terraform plan -out main.tfplan -no-color 
          -var environment_prefix="${{ inputs.environment }}" 
          -var sql_instance_name="${{ secrets.AZURE_SQL_INSTANCE_NAME }}"
          -var sql_server_ad_admin_object_id="${{ secrets.AZURE_SQL_SERVER_AD_ADMIN_OBJECT_ID }}"
          -var sql_server_ad_admin_username="${{ secrets.AZURE_SQL_SERVER_AD_ADMIN_USERNAME }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Apply Main
        id: apply
        working-directory: "./artifacts/${{inputs.artifactNameTerraform}}"
        run: |
          terraform apply main.tfplan

          $resource_group_name=$(terraform output resource_group_name)
          Write-Output "::set-output name=resource_group_name::$($resource_group_name)"

          $api_app_name=$(terraform output api_app_name)
          Write-Output "::set-output name=api_app_name::$($api_app_name)"

          $static_website_name=$(terraform output static_website_name)
          Write-Output "::set-output name=static_website_name::$($static_website_name)"

          $static_website_url=$(terraform output static_website_default_host_name)
          $static_website_url="https://${static_website_url}".replace('"', "")
          
          echo "${static_website_url}"
          Write-Output "::set-output name=static_website_url::$($static_website_url)"
        shell: pwsh
        
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Get static website api key
        id: get_config_key
        run: >
          $api_key=$(az staticwebapp secrets list --name ${{ steps.apply.outputs.static_website_name }} 
          --query properties.apiKey 
          --output tsv)

          Write-Output "::add-mask $($api_key)"
          
          Write-Output "::set-output name=api_key::$($api_key)"
        shell: pwsh