name: IaC

on:
  workflow_call:
    inputs:
      artifactNameAPI:
        required: true
        type: string
      artifactNameSql:
        required: true
        type: string
      artifactNameTerraform:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_USERNAME:
        required: true
      AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_PASSWORD:
        required: true
      AZURE_SQL_INSTANCE_NAME:
        required: true
      AZURE_SQL_DATABASE_PRODUCTCATALOGUE_CONNECTION_STRING:
        required: true
    outputs:
      static_website_url:
        value: ${{ jobs.infrastructure_create.outputs.static_website_url }}

jobs:
  infrastructure_create:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      static_website_url: ${{ steps.static_website_settings.outputs.static_website_url }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: build static website
        working-directory: ./UI
        run: >
          npm install

          echo >> .env.production
          
          echo VITE_PRODUCT_CATALOGUE_API_URL="https://mrmclangley${{ inputs.environment }}productcatalogue.azurewebsites.net/" >> .env.production
          
          npm run build

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_wrapper: false

      - name: Terraform Init Main
        id: init
        working-directory: "./artifacts/${{inputs.artifactNameTerraform}}"
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Plan Main
        id: plan
        working-directory: "./artifacts/${{ inputs.artifactNameTerraform }}"
        run: > 
          terraform plan -out main.tfplan -no-color 
          -var sql_instance_administrator_login_username="${{ secrets.AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_USERNAME }}" 
          -var sql_instance_administrator_login_password="${{ secrets.AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_PASSWORD }}" 
          -var environment_prefix="${{ inputs.environment }}" -var sql_instance_name="${{ secrets.AZURE_SQL_INSTANCE_NAME }}"
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Apply Main
        id: apply
        working-directory: "./artifacts/${{inputs.artifactNameTerraform}}"
        run: |
          terraform apply main.tfplan

          resource_group_name=$(terraform output resource_group_name)
          echo "::set-output name=resource_group_name::$resource_group_name"

          api_app_name=$(terraform output api_app_name)
          echo "::set-output name=api_app_name::$api_app_name"

          sql_instance_name=$(terraform output sql_instance_name)
          echo "::set-output name=sql_instance_name::$sql_instance_name"

          sql_database_name=$(terraform output sql_database_name)
          echo "::set-output name=sql_database_name::$sql_database_name"

          static_website_name=$(terraform output static_website_name)
          echo "::set-output name=static_website_name::$static_website_name"
        
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Init Terraform Firewall rules
        working-directory: "./artifacts/${{inputs.artifactNameTerraform}}/firewall-rules"
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Plan Terraform Firewall rules
        working-directory: "./artifacts/${{inputs.artifactNameTerraform}}/firewall-rules"
        run: terraform plan -out main.tfplan -no-color
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Apply Terraform Firewall rules
        working-directory: "./artifacts/${{inputs.artifactNameTerraform}}/firewall-rules"
        run: terraform apply main.tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Get static website api key
        id: staticWebConfig
        run: >
          $api_key=$(az staticwebapp secrets list --name ${{ steps.apply.outputs.static_website_name }} 
          --query properties.apiKey 
          --output tsv)

          Write-Output "::add-mask $($api_key)"
          
          Write-Output "::set-output name=api_key::$($api_key)"
        shell: pwsh

      - name: Build and deploy static web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "${{ steps.staticWebConfig.outputs.api_key }}"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "UI/build/static"
          output_location: ""
          skip_app_build: true
      
      ## A B1 webapp doesn't have slots so I don't think its possible to deploy to a B1 webapp using azure/webapps-deploy@v2
      - name: Deploy api source code
        working-directory: artifacts/${{inputs.artifactNameAPI}}
        run: > 
          az webapp deployment source config-zip 
          -g ${{ steps.apply.outputs.resource_group_name }} 
          -n ${{ steps.apply.outputs.api_app_name }} --src api.zip
      
      - name: Acquire connection strings
        id: setSqlConnection
        run: >
          $raw_connection_string = $(az sql db show-connection-string 
          -s ${{ steps.apply.outputs.sql_instance_name }} 
          -n ${{ steps.apply.outputs.sql_database_name }} -c ado.net)
          
          $connection_string_tcp = 
          $raw_connection_string.Replace("<password>", "${{ secrets.AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_PASSWORD }}")
          
          $connection_string_tcp = 
          $connection_string_tcp.Replace("<username>", "${{ secrets.AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_USERNAME }}")
          
          Write-Output "::set-output name=connection_string_tcp::'$($connection_string_tcp)'"
          
          $manual_connection_string = 
          $raw_connection_string.Replace("<password>", "${{ secrets.AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_PASSWORD }}")
          
          $manual_connection_string = 
          $manual_connection_string.Replace("<username>", "${{ secrets.AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_USERNAME }}")
          
          $manual_connection_string = $manual_connection_string.Replace("Server=tcp:", "Server=")
          
          $manual_connection_string = $manual_connection_string.Replace(",1433", "")
          
          Write-Output "::set-output name=manual_connection_string::$($manual_connection_string)"
        shell: pwsh

      - name: Setup connection string for webapp
        id: static_website_settings
        run: > 
          az webapp config connection-string set -g ${{ steps.apply.outputs.resource_group_name }} 
          -n ${{ steps.apply.outputs.api_app_name }} -t SQLAzure 
          --settings ProductCatalogue='${{ steps.setSqlConnection.outputs.connection_string_tcp }}'

          $static_website_url =  'https://' + (az staticwebapp show --name ${{ steps.apply.outputs.static_website_name }} 
          --query defaultHostname --output tsv)

          az webapp config appsettings set -g ${{ steps.apply.outputs.resource_group_name }}
          -n ${{ steps.apply.outputs.api_app_name }} --settings Cors__AllowedOrigins__0=$static_website_url
          
          Write-Output "::set-output name=static_website_url::$($static_website_url)"
        shell: pwsh
    
      - name: Azure SQL Deploy
        uses: azure/sql-action@v1.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_DATABASE_PRODUCTCATALOGUE_CONNECTION_STRING }}
          sql-file: "./artifacts/${{inputs.artifactNameSql}}/product-catalogue-migration-script.sql"
  
      - name: 'Logout az'
        run: az logout