name: build-test-base

on:
  workflow_call:
    inputs:
      artifactNamePostman:
        required: true
        type: string

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
          name: ${{ inputs.artifactNamePostman }}

      - run: ls -R
        working-directory: "./artifacts"

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: |
          newman run 'artifacts/Product Catalogue.postman_collection.json' -e 'artifacts/Product Catalogue.postman_environment.json' -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: postman.tests.result
          path: 'testResults'