name: integration_test_orchestration

on:
  workflow_call:
    inputs:
      artifactNamePostman:
        required: true
        type: string
      static_website_url:
        required: true
        type: string

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
          name: ${{ inputs.artifactNamePostman }}

      - run: ls -R
        working-directory: "./artifacts"

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: >
          newman run 'artifacts/Product Catalogue.postman_collection.json' 
          -e 'artifacts/Product Catalogue.postman_environment.json' 
          -r htmlextra 
          --reporter-htmlextra-export testResults/htmlreport.html 
          --reporter-htmlextra-darkTheme  > testResults/runreport1.html

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: postman.tests.result
          path: 'testResults'
          
  playwright:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      
      - name: Setup configuration
        working-directory: ./UI
        run: > 
          New-Item .env.development -type file

          Write-Output ${{ inputs.static_website_url }}
          
          Add-Content -Path .env.development -Value 'VITE_PRODUCT_CATALOGUE_API_URL="https://localhost"'
          
          Add-Content -Path .env.development -Value 'PLAYWRIGHT_BASE_URL="${{ inputs.static_website_url }}/"'
        shell: pwsh

      - name: Install dependencies
        working-directory: ./UI
        run: npm install

      - name: Install Playwright Browsers
        working-directory: ./UI
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./UI
        run: npx playwright test --workers 6 --retries=3

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30