name: orchestration

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build-test-base.yml
    with:
      artifactNameAPI: product-catalogue
      artifactNameSql: migration-script
      artifactNameTerraform: terraform
      artifactNamePostman: postman

  IaC:
    needs: build
    uses: ./.github/workflows/infastructure-deploy-destroy.yml
    with:
      artifactNameAPI: product-catalogue
      artifactNameSql: migration-script
      artifactNameTerraform: terraform
      environment: dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_USERNAME: ${{ secrets.AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_USERNAME }}
      AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_PASSWORD: ${{ secrets.AZURE_SQL_INSTANCE_ADMINISTRATOR_LOGIN_PASSWORD }}
      AZURE_SQL_INSTANCE_NAME: ${{ secrets.AZURE_SQL_INSTANCE_NAME }}