name: build_orchestration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build.unit.test.package.yml
    with:
      artifactNameAPI: product-catalogue-api
      artifactNameSqlMigration: migration-script
      artifactNameTerraform: terraform
      artifactNamePostman: postman
      artifactNameStaticWebsite: product-catalogue-static-ui
      environment: dev