name: orchestration

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build-unit-test-package.yml
    with:
      artifactNameAPI: product-catalogue-api
      artifactNameSqlMigration: migration-script
      artifactNameSqlAzureAdPermissions: azure-ad-permissions
      artifactNameTerraform: terraform
      artifactNamePostman: postman

  iac:
    needs: build
    uses: ./.github/workflows/infrastructure-create.yml
    with:
      artifactNameAPI: product-catalogue-api
      artifactNameSqlMigration: migration-script
      artifactNameSqlAzureAdPermissions: azure-ad-permissions
      artifactNameTerraform: terraform
      environment: dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SQL_INSTANCE_NAME: ${{ secrets.AZURE_SQL_INSTANCE_NAME }}
      AZURE_SQL_DATABASE_PRODUCTCATALOGUE_CONNECTION_STRING: ${{ secrets.AZURE_SQL_DATABASE_PRODUCTCATALOGUE_CONNECTION_STRING }}

  integration_tests:
    needs: iac
    uses: ./.github/workflows/integration-tests.yml
    with:
      artifactNamePostman: postman
      static_website_url: ${{ needs.iac.outputs.static_website_url }}

  iac_destroy:
    needs: integration_tests
    uses: ./.github/workflows/infrastructure-destroy.yml
    with:
      artifactNameTerraform: terraform
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}