name: orchestration

on:
  push:
    branches: [ "0.0.6.azure.ad" ]

jobs:
  build:
    uses: ./.github/workflows/build.unit.test.package.yml
    with:
      artifactNameAPI: product-catalogue-api
      artifactNameSqlMigration: migration-script
      artifactNameSqlAzureAdPermissions: azure-ad-permissions
      artifactNameTerraform: terraform
      artifactNamePostman: postman
      artifactNameStaticWebsite: product-catalogue-static-ui
      environment: dev

  integration_tests:
    needs: build
    uses: ./.github/workflows/integration.tests.yml
    with:
      artifactNamePostman: postman
      static_website_url: https://brave-bay-01e132503.1.azurestaticapps.net